version: "3.3"

services:
  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=car-data-center
      - MYSQL_USER=car-data-center
      - MYSQL_PASSWORD=car-data-center
    command: mysqld
      --character-set-server=utf8mb3
      --collation-server=utf8mb3_bin
      --sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
      --innodb-file-format=Barracuda
      --innodb-file-per-table=true
      --innodb-large-prefix=true
      --max-allowed-packet=4M