FROM node:13.6.0-alpine3.10
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm i
COPY ./tsconfig.json ./
COPY ./src ./src
COPY ./test ./test
COPY ./ormconfig.js ./
RUN ls -la
CMD ["npm", "run", "test:e2e:run"]