version: "3.3"

services:
  db:
    image: mysql:5.6
    restart: always
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=car-data-center
        - MYSQL_USER=car-data-center
        - MYSQL_PASSWORD=car-data-center
    command: mysqld
        --character-set-server=utf8mb3
        --collation-server=utf8mb3_bin
        --sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
        --innodb-file-format=Barracuda
        --innodb-file-per-table=true
        --innodb-large-prefix=true
        --max-allowed-packet=4M

    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile.car-app
    command: /bin/bash -c "sleep 10s; npx typeorm migration:run; node /dist/main.js"
    ports:
      - "3000:3000"
    environment:
      BASE_URL: http://api:3000
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: car-data-center
      DB_MYSQL_PASSWORD: car-data-center
      DB_MYSQL_DATABASE: car-data-center
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: